version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: master
user:
  default_owner: null
  default_tier: null
current:
  spec: .specwright/specs/rename-to-finalform.md
  aip: .specwright/aips/rename-to-finalform.yaml
